### ISSUE TITLE
सीयते or सायते ?

### ISSUE THREAD

**Issue by aniruddha753** [drdhaval2785/SanskritVerb#1079] opened 2018-10-20 16:58 UTC
Should the कर्मणि-लट् form for षै in प्रथमैकवचन not be सीयते? The tool shows सायते [here](https://www.sanskritworld.in/sanskrittool/SanskritVerb/panini.php?first=%E0%A4%B7%E0%A5%88&upasarga=&lakAra=law&sanAdi=&tran=SLP1&vAcya=karma&frontend=1&jsonmode=0&number=01.1063&removed_sutras=&step=12&type=tiGanta).

**Comment by mrudani** [comment] 2018-10-21 09:52
केन ईत्वं भवति, घुमास्था... सूत्रे तु सा इति षोधातोः ग्रहणात् न तस्यात्र
प्रवृत्तिः।

On Oct 20, 2018 10:28 PM, "aniruddha753" <notifications@github.com> wrote:

Should the कर्मणि-लट् form for षै in प्रथमैकवचन not be सीयते? The tool
shows सायते here
<https://www.sanskritworld.in/sanskrittool/SanskritVerb/panini.php?first=%E0%A4%B7%E0%A5%88&upasarga=&lakAra=law&sanAdi=&tran=SLP1&vAcya=karma&frontend=1&jsonmode=0&number=01.1063&removed_sutras=&step=12&type=tiGanta>
.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/drdhaval2785/SanskritVerb/issues/1079>, or mute the
thread

**Comment by aniruddha753** [comment] 2018-10-21 11:35
I read in the book "sheeghrabodh vyaakaran". Following is the page which says 'saa' is to be converted to 'see'. ![image](https://user-images.githubusercontent.com/13087420/47266382-33a12200-d553-11e8-9175-b843017dec98.png)

**Comment by mrudani** [comment] 2018-10-21 12:03
तत्र पश्यतु सो इति दत्तम् अष्टाध्यायीसहजबोधेपि।

**Comment by aniruddha753** [comment] 2018-10-21 15:15
Sorry, did not get it. I thought the eight aakaarant dhatoo which become 'ee' are not tied to those examples mentioned above on the page.
I looked at the sutra 'घुमास्थागापाजहातिसां हलि'. I'm not sure, but looks like 'saa' is included in them. Found this line of commentary: "घुसंज्ञाकानाम् अङ्गानां, मा स्था गा पा जहाति सा इत्येतेषां हलादौ क्ङिति प्रत्यये परतः ईकारादेशो भवति".

**Comment by mrudani** [comment] 2018-10-22 17:12
तत्र सा इति यः उक्तः सः षो इति धातुः।

**Comment by drdhaval2785** [comment] 2018-12-17 13:52
https://www.sanskritworld.in/sanskrittool/SanskritVerb/Data/dhaatupaatha/files-6-9-2014/mA579.html clearly says that it will be sAyate. 

Closing this issue. It is not a bug.

**Closed by drdhaval2785** 2018-12-17 13:52 UTC
